### ISSUE TITLE
mac下运行直接空指针了。

### ISSUE THREAD

**Issue by jixuan1989** [lzqwebsoft/Mp3-Player#2]
如题，jdk7. 在启动界面的时候，直接空指针：
Exception in thread "main" java.lang.NullPointerException
    at javax.swing.plaf.metal.MetalSliderUI.installUI(MetalSliderUI.java:110)
    at javax.swing.JComponent.setUI(JComponent.java:664)
    at javax.swing.JSlider.setUI(JSlider.java:313)
    at org.websoft.widget.ControllePane.<init>(ControllePane.java:36)
    at org.websoft.widget.PlayWindow.<init>(PlayWindow.java:131)
    at org.websoft.widget.PlayWindow.main(PlayWindow.java:609)

错误的那行代码是:   progressBar.setUI(new ProgressSliderUI());
同样 volumn那个也报错。 
屏蔽掉就能运行了。。。

**Comment by lzqwebsoft** [comment]
mac下面没有能测试啊，progressBar.setUI()有错，说明调控声音的那个滑动条组件设置成三角形的外观有问题，可将其设置成默认的，不知可否将progressBar.setUI(new ProgressSliderUI());注释掉~
